flutter/impeller

- tools/build_metal_library.py
See discussion on https://github.com/flutter/engine/pull/31227
@chinmaygarde hopefully this is all you had in mind for this?
> Use -M0 instead of -frecord-sources

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Impeller changes related to https://github.com/flutter/engine/pull/31491
> adopt new DlColorFilter objects

- renderer/backend/metal/formats_mtl.h
- renderer/backend/metal/render_pass_mtl.mm
- renderer/command.h
- renderer/formats.h
Also fix import order in formats.
> Add cull mode to command

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Changes needed to land https://github.com/flutter/engine/pull/31535
> changes for new DlMaskFilter objects

- geometry/path_builder.cc
- geometry/path_builder.h
Fixes https://github.com/flutter/flutter/issues/99032.
I couldn't spot any math errors, so I ended up making some immediate mode manipulator widgets to work out that there's nothing wrong with the curves themselves (PRs incoming). :)
Skia: https://fiddle.skia.org/c/91fcb500e2923b4a787142f86d8b10db
Impeller:
https://user-images.githubusercontent.com/919017/155478165-6ca939d1-2555-42c1-a631-f16dd1a5f309.mov
> Match skia's path param ordering

- display_list/display_list_dispatcher.cc
Needed for https://github.com/flutter/engine/pull/31672
> adopt new DlAttributeType enum naming

- geometry/geometry_unittests.cc
- geometry/point.h
Used in https://github.com/flutter/impeller/pull/35.
> Add dot and cross product to Point

- .github/dependabot.yml
- .github/workflows/scorecards-analysis.yml
This will also add dependabot to auto update the workflows dependencies.
Bug: https://github.com/flutter/flutter/issues/99185
If you need help, consider asking for advice on the #hackers-new channel on [Discord].
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
> Remove schedule runs of scorecards.

- typographer/text_render_context.cc
Found while [rolling impeller](https://github.com/flutter/engine/pull/31688).
> Fix license to make the license script happy

- entity/contents.cc
- entity/contents.h
- entity/entity_unittests.cc
For adding the rest of the caps and joins.
Part of https://github.com/flutter/flutter/issues/99089.
> Setup join/cap proc

- geometry/geometry_unittests.cc
- geometry/point.h
Used in https://github.com/flutter/impeller/pull/52.
> Point: Add reflect, allow mul/div with any arithmetic types, add RHS operators for arithmetic types

- geometry/geometry_unittests.cc
Closes https://github.com/flutter/flutter/issues/99772
> Correct polyline bounds test

- playground/playground.mm
This has been bothering me for a while, so I decided to look into it today.
https://user-images.githubusercontent.com/919017/157591706-d73d30ae-babd-4676-a8d4-22f243aa65fa.mov
> Prevent hanging when running back-to-back playground tests

- compiler/BUILD.gn
- display_list/display_list_dispatcher.cc
- renderer/backend/metal/render_pass_mtl.mm
- renderer/renderer.h
- tools/impeller.gni
Part of https://github.com/flutter/engine/pull/31959
> Document GN rules and make targets that cannot be built on the platform be no-ops.

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Will unblock https://github.com/flutter/engine/pull/31981
> Use new DlColorSource objects

- display_list/display_list_dispatcher.cc
Should have gone in with https://github.com/flutter/impeller/pull/73
> update the linear gradient code to the new accessor names

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Added in https://github.com/flutter/engine/pull/32050
> Implement DisplayListDispatcher::transformReset.

- aiks/aiks_unittests.cc
- aiks/canvas.cc
- aiks/canvas.h
- display_list/display_list_dispatcher.cc
- entity/BUILD.gn
- entity/contents/clear_contents.cc
- entity/contents/clear_contents.h
> Add ClearContents to apply specified contents to the entire render target.

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Will unblock  https://github.com/flutter/engine/pull/32026
> Use new DlBlendMode object

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Enables engine PR https://github.com/flutter/engine/pull/32140
> switch dispatcher methods to new DlImageFilter objects

- entity/contents/text_contents.cc
Also updates comments that were first written when this wasn't batched.
For some reason, in the original implementation, I had assumed that
styling information was not already in a uniform.
> Batch all draw calls in the entire text frame.

- display_list/display_list_dispatcher.cc
- display_list/display_list_playground.cc
- display_list/display_list_playground.h
- display_list/display_list_unittests.cc
- geometry/constants.h
- geometry/path_builder.cc
- geometry/path_builder.h
https://user-images.githubusercontent.com/919017/160776919-6250bea2-d95b-4f01-8d80-cfe215a63ae9.mov
Here's a version with extra geometry to show where each cubic begins:
https://user-images.githubusercontent.com/919017/160776998-c0b1f5b1-d693-4ce7-9134-5db84097f5f9.mov
> Implement drawArc

- display_list/display_list_dispatcher.cc
- display_list/display_list_dispatcher.h
Will unblock https://github.com/flutter/engine/pull/32329
> support new DlVertices object in dispatcher

- aiks/aiks_unittests.cc
- display_list/display_list_unittests.cc
- geometry/geometry_unittests.cc
- geometry/path.cc
- geometry/path_builder.cc
> Remove extra point from DrawRect; skip over duplicate contour points

- base/BUILD.gn
Fixes the build at HEAD.
File removed in #117.
> Remove base.h from base/BUILD

- renderer/backend/metal/command_buffer_mtl.mm
Fixes symbol exposure that resulted in revert in https://github.com/flutter/engine/pull/32677
Apple Clang doesn't hide these even though Fuchsia Clang does.
The diff is confusing because I re-arranged some code, but this did not actually delete any lines.
> Move static methods to anonymous namespace

- compiler/BUILD.gn
- compiler/code_gen_template.h
- compiler/compiler.cc
- compiler/compiler.h
- compiler/compiler_backend.cc
- compiler/compiler_backend.h
- compiler/compiler_test.cc
- compiler/compiler_test.h
- compiler/compiler_unittests.cc
- compiler/impellerc_main.cc
- compiler/includer.cc
- compiler/includer.h
- compiler/logger.h
- compiler/reflector.cc
- compiler/reflector.h
- compiler/source_options.cc
- compiler/source_options.h
- compiler/switches.cc
- compiler/switches.h
- compiler/types.cc
- compiler/types.h
- tools/impeller.gni
Also parameterize all unit-tests so all backends are automatically tested.
> Add impellerc options to compile OpenGL Desktop and ES variant shaders.
