display_list/display_list_dispatcher.cc, display_list/display_list_dispatcher.h
Trying to compensate for the change to `saveLayer()` in https://github.com/flutter/engine/pull/30957.
=> Compensate for change to saveLayer

aiks/aiks_playground.cc, entity/entity_playground.cc, playground/BUILD.gn, playground/playground.h, playground/playground.mm, tools/impeller.gni
Adds a GN build-time flag for enabling the unit test playgrounds. Goes along with https://github.com/flutter/engine/pull/31280, which adds the flag to `flutter/tools/gn`.
=> Adds a GN flag for playgrounds

geometry/geometry_unittests.cc, geometry/rect.h
Fix `Rect::Compare` to use origin + size for bottom and right compare.
=> Fix Rect::Contains bugs

renderer/backend/metal/formats_mtl.h, renderer/backend/metal/render_pass_mtl.mm, renderer/command.cc, renderer/command.h, renderer/formats.h, renderer/vertex_buffer.h, renderer/vertex_buffer_builder.h
Draw calls spanning a >64k vertex window are the rare case in most renderers. In the entities/displaylist renderer we'll probably prefer to split uncommon large draws into multiple calls in favor of the large index buffer memory/bandwidth savings on mobile.
Splitting big draw calls is trivial with the presence of the `baseVertex` param in Metal or `glDrawElementsBaseVertex` in GLES (will add in follow-up).
=> Support 16bit index buffers

geometry/geometry_unittests.cc, geometry/rect.h, renderer/backend/metal/render_pass_mtl.mm, renderer/command.h, renderer/formats.h
Used optionals for these because the default behavior with their absence will be similar across graphics backends.
Most modern APIs support multiple viewports and multiple scissor rects (not sure about driver coverage though), but GLES3 does not.
I think it's reasonable to include these as command params against all rendering backends. In Vulkan, we'd flip these on as [dynamic state](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDynamicState.html) in pipelines and then set them with commands.
Used these in an [imgui backend](https://github.com/bdero/impeller/blob/3ac316755d016f7ea25c8e4504d5b5a151dd226a/bdero_pbr/imgui/imgui_impl_impeller.cc#L184-L188) that targets impeller 🙂 :
https://user-images.githubusercontent.com/919017/154174965-91656bd4-3bdf-408c-8643-94aa …
=> Add viewport and scissor support

aiks/aiks_unittests.cc, aiks/canvas.cc, aiks/canvas.h, entity/content_context.cc, entity/content_context.h, entity/contents.cc, entity/contents.h, entity/entity_pass.h, renderer/pipeline_builder.h
Fixes https://github.com/flutter/flutter/issues/98631.
Restoration works with a single draw call:
- When clip paths are added, they increase the stencil height only if the stencil matches the current depth. So higher depths are always a subset of lower depths.
- When popping the canvas stack, an entity is appended to run a draw call which max bounds the stencil to the previous depth.
=> Support nested clips & clip state restoration

renderer/command.cc
Fixes a bug introduced in c535672 which broke a bunch of tests (this slipped under the radar for a while likely because I ran the wrong test filter and all my other PRs are based before 78bc2a02 because https://github.com/flutter/engine/pull/31491 wasn't merged yet).
=> Fix breaking vertex binding bug

renderer/backend/metal/render_pass_mtl.mm
Forgot to patch this line in back when I pulled the 16 bit buffers patch out of another branch.
=> Fix index size check to respect 16 bit buffers

geometry/BUILD.gn, geometry/geometry_unittests.cc, geometry/point.h, geometry/type_traits.cc, geometry/type_traits.h
Also adds missing RHS operator overloads for TSize.
For any algebraic ops involving TPoint and TSize:
1. `TPoint` takes precedent over `TSize`.
2. Floating point types take precedent over integer types.
3. If there's a tie (for example: `TPoint<int> + TPoint<long long>`), the LHS takes precedent.
=> Add mixed type specializations on algebraic ops in TPoint

aiks/aiks_unittests.cc, entity/contents.cc
Fixes https://github.com/flutter/flutter/issues/98681.
The only relevant changes are in `entity/contents.cc` and `aiks/aiks_unittests.cc`. This PR depends on/includes the changes in https://github.com/flutter/impeller/pull/21.
=> Respect TextureContents/Canvas::DrawImageRect source rect

playground/BUILD.gn, playground/imgui/BUILD.gn, playground/imgui/imgui_impl_impeller.cc, playground/imgui/imgui_impl_impeller.h, playground/imgui/imgui_raster.frag, playground/imgui/imgui_raster.vert, playground/playground.mm
Depends on https://github.com/flutter/engine/pull/31541 and https://github.com/flutter/buildroot/pull/549.
The backend mimics the [many existing ImGui rendering backends](https://github.com/ocornut/imgui/tree/master/backends), which might make it a good candidate for upstreaming if we happen to offer standalone Impeller builds in the future.
ImGui commands can be used anywhere within the playground render loop.
For example, here's a simple modification of `RendererTest.CanRenderMultiplePrimitives`:
```cpp
ImGui::Begin("Controls");
static float weight;
ImGui::SliderFloat("Weight", &weight, 0, 1);
FS::FrameInfo frame_info;
frame_info.current_time = fml::TimePoint::Now().ToEpochDelta().ToSecondsF();
frame_info.cursor_position =
Point(weight * pass.GetRenderTargetSize().width, 0); …
```
=> Add an ImGui backend targetting Impeller to the playground

playground/imgui/imgui_impl_impeller.cc
Fix breakage found while rolling impeller: https://github.com/flutter/engine/pull/31637
* Add maybe_unused for assert elided in release.
* Also address [this comment](https://github.com/flutter/impeller/pull/20#discussion_r812280396) (doesn't cause a problem, but noticed I failed to push this prior to merge because of the breakage).
=> Fix prod build

entity/entity_playground.cc, entity/entity_playground.h
Add a convenience `OpenPlaygroundHere` overload to the entity playground which supplies the `ContentContext` to a render callback.
=> Add entity playground callback

compiler/reflector.cc, entity/contents.cc, entity/entity_unittests.cc, entity/shaders/solid_stroke.frag, entity/shaders/solid_stroke.vert, geometry/geometry_unittests.cc, geometry/path.cc, geometry/path.h, geometry/path_builder.cc, geometry/path_component.h, renderer/tessellator.cc, renderer/tessellator.h
Addresses the https://github.com/flutter/flutter/issues/99032#issuecomment-1050192450 part of 99032 by supporting strokes.
Does not fix the weird issues related to winding (?) for the strokes in that test case.
Adds two test cases: a simple case where a stroke has three subcontours (i.e. two MoveTo commands after some drawing), and a slightly more complicated case of drawing multiple segments (square) moving and then more segments (triangle).
The basic algorithm is:
- Introduces a Polyline struct with the original point vector and a set indicating which indices represent a move to point.
- Add an input to the vertex shader about whether the pen is down, and pass it along to the fragment shader. If it is <1, draw a transparent pixel.
- The pen is down whenever we're traversing the polyline …
=> Support subcontours in strokes, lay groundwork for fills

playground/BUILD.gn, playground/widgets.cc, playground/widgets.h
Depends on https://github.com/flutter/impeller/pull/26.
Widgets reset when pressing the R key.
Example usage:
```cpp
TEST_F(EntityTest, CubicCurveToTest) {
EntityPlaygroundCallback callback = [&](ContentContext& context,
RenderPass& pass) -> bool {
Point a1, a2;
std::tie(a1, a2) = IMPELLER_PLAYGROUND_LINE(
Point(222, 130), Point(122, 156), 10, Color::Black(), Color::White());
Point b1, b2;
std::tie(b1, b2) = IMPELLER_PLAYGROUND_LINE(
Point(162, 151), Point(84, 160), 10, Color::Black(), Color::White());
Path path =
PathBuilder{}.MoveTo(a1).CubicCurveTo(a2, b2, b1).Close().TakePath();
Entity entity;
entity.SetPath(path);
entity.SetContents(SolidColorContents::Make(Color::Red()));
return entity.Render(context, pass);
};
ASSERT_TRUE(OpenPlaygroundHere(callback));
}
``` …
=> Add immediate mode manipulator widget macros for the playground

entity/entity_unittests.cc, renderer/tessellator.cc
Fixes flutter/flutter#99032
Related to https://github.com/flutter/impeller/pull/31
Tessellates individual contours of a polyline separately, to avoid treating `MoveTo` commands as introducing new contours. Removes the `DISABLED` from the test cases, since they now render the same as Skia.
=> Fix MoveTo for fills

geometry/geometry_unittests.cc, geometry/path.cc
This PR is chained on top of https://github.com/flutter/impeller/pull/33.
Used in https://github.com/flutter/impeller/pull/35.
Removing duplicate points between connected components makes generating clean stroke geometry easier.
=> Remove duplicate points between connected components when generating polylines

entity/contents.cc, entity/contents.h, entity/entity_unittests.cc
This PR is chained on top of https://github.com/flutter/impeller/pull/33 and https://github.com/flutter/impeller/pull/34.
Part of https://github.com/flutter/flutter/issues/99089.
This is a rewrite of the stroke algo that fixes the contour body generation and supports caps+joins. So far I added a simple bevel join, but will add all the rest of the caps+joins in followup(s).
Also, a join isn't being generated for closed paths yet.
https://user-images.githubusercontent.com/919017/155720946-95e0cbfd-d19a-4eea-95cd-c340ac24ad13.mov
=> Generate correct stroke geometry for connected points & support caps+joins

entity/contents.cc, geometry/geometry_unittests.cc, geometry/path.cc, geometry/path.h, geometry/path_builder.cc, geometry/path_component.cc, geometry/path_component.h, renderer/tessellator.cc
Fixes https://github.com/flutter/flutter/issues/99177.
Also part of https://github.com/flutter/flutter/issues/99089.
* `break`s are now `contour`s. They can never be empty, and the first contour is included in polylines (unless the path contains nothing).
* A contour component is always inserted at 0, 0.
* Closing a contour starts a new contour (bug fix).
* Contours track `is_closed` state. This is unique information which can't be derived from point data.
* Stroke content generates a final join for closed paths:
https://user-images.githubusercontent.com/919017/155943419-1388d943-0d62-4355-9f64-991bddf2672f.mov
* Contours are guaranteed to never be empty:
* Contiguous contour components are overridden while the path is being formed.
* When generating polylines, the last contour is elided …
=> Remove break corner cases, simplify strokes, and generate closed path joins

entity/contents.cc, typographer/backends/skia/text_frame_skia.cc, typographer/backends/skia/text_render_context_skia.cc, typographer/font.cc, typographer/font.h
Fixes the remaining issues w.r.t glyph atlases in the previous commit.
=> Account for glyph extents in the atlas.

entity/contents.cc, entity/contents.h, entity/entity_unittests.cc, geometry/geometry_unittests.cc, geometry/scalar.h
Part of https://github.com/flutter/flutter/issues/99089.
* No trig or sqrt.
* Default join is now miter (like Skia).
* Default miter limit is 4 (also like Skia).
* The demo starts with a miter limit just above `sqrt(2)` so that right angles are just under the limit and acute angles are over the limit (causing them to get beveled).
https://user-images.githubusercontent.com/919017/156109760-fc594d38-d13d-4377-8e65-3b5e6a4e5d0c.mov
=> Add miter join

entity/contents.cc, entity/contents.h, entity/entity_unittests.cc, geometry/path_builder.cc, geometry/path_builder.h
Depends on https://github.com/flutter/impeller/pull/49 (miter join) and https://github.com/flutter/impeller/pull/51 (add vector reflect to point).
Part of https://github.com/flutter/flutter/issues/99089.
* As part of this, I moved the cubic handle arc constant to `path_builder.h` and added a comment to describe how to use it for approximating arcs.
* The smooth scaling is a somewhat arbitrary asymptote against stroke width. I just tried a few things and this ended up looking pretty reasonable for really big/small strokes. For enormous strokes it's diminishing returns, so we can probably adjust this to make it better.
https://user-images.githubusercontent.com/919017/156336997-405b4b14-b666-4479-9816-cdb162d2adbb.mov
I experimented with a couple of weird ideas at first before falling back …
=> Add round caps and joins

geometry/geometry_unittests.cc
Looks like I forgot to update this test when adjusting the default tolerance.
=> Fix ScalarNearlyEqual test

geometry/color.h, geometry/geometry_unittests.cc, geometry/geometry_unittests.h
Convert to/from premultiplied alpha colors.
Used in https://github.com/flutter/impeller/pull/55.
=> Add color premultiply/unpremultiply

README.md, aiks/BUILD.gn, archivist/BUILD.gn, base/BUILD.gn, base/config.h, entity/BUILD.gn, geometry/matrix_decomposition.h, geometry/path.cc, geometry/path_builder.h, geometry/scalar.h, image/BUILD.gn, renderer/BUILD.gn, tessellator/BUILD.gn, tessellator/tessellator.cc, tools/impeller.gni, typographer/BUILD.gn
//flutter/fml depends on the Dart VM for _at least_ tracing and the implementation of `TimePoint::Now`. This is a very heavy dependency for the tessellation library, which really doesn't need it.
I've done the following:
- Dropped the FML dependency from `impeller_component`.
- Added the dependency to targets that still use it.
- Removed the dependency from `//flutter/impeller/geometry`, which only used it for some macros and DCHECKs
- Removed the dependency from `//flutter/impeller/tessellator`, which only used it for a single trace event.
=> Remove FML dependency on geometry, tessellator

fixtures/sample.vert, geometry/BUILD.gn, geometry/constants.cc, playground/imgui/BUILD.gn, playground/imgui/imgui_impl_impeller.cc, playground/imgui/imgui_impl_impeller.h, playground/imgui/imgui_raster.frag, playground/imgui/imgui_raster.vert, tools/check_licenses.py
Also fixes the files with missing licenses. This check is somewhat easy with
Impeller than in the engine because all source files must have the same license
block.
Resolves an action item in the umbrella issue https://github.com/flutter/flutter/issues/97686
The script may eventually be run as part of a CI step.
=> Add a script that checks that all source files have a valid license block.

entity/contents/content_context.h, entity/shaders/solid_stroke.frag
While writing https://github.com/flutter/impeller/pull/68 I noticed visible geometry appearing between disconnected contours in the entity tests. It turns out I accidentally set the default blend mode to `kSource` rather than `kSourceOver` when adding blend modes, and I forgot to update the stroke shader to respect premultiplied source colors.
@chinmaygarde Was this the path-related regression you mentioned earlier?
Before:
After:
=> Correct default blend mode, fix solid stroke shader to respect premultiplied source colors

entity/BUILD.gn, entity/contents/content_context.h, entity/contents/filter_contents.cc, entity/contents/filter_contents.h, entity/entity.cc, entity/entity.h, entity/entity_pass.cc, entity/entity_unittests.cc
Part of https://github.com/flutter/flutter/issues/99521.
* Add `FilterContents` class that take zero or more texture inputs and generates a result texture.
* Any input may either be an `impeller::Texture` or another `FilterContents` which will get resolved at render time.
* When the `FilterContents` is rendered with an entity, it draws the output texture to the parent pass via `TextureContents` and respects the entity's transform/stencil/path.
* By default, the size of the first input texture is used as the size of the result texture, but filters may override this behavior depending on the use case. For example, a convolution filter (such as a Gaussian blur) may optionally increase the size of the result texture by a factor of the blur radius.
* Add `BlendFilterContents` filter for simple …
=> Chainable texture filters

BUILD.gn, aiks/BUILD.gn, archivist/BUILD.gn, base/BUILD.gn, compiler/BUILD.gn, entity/BUILD.gn, image/BUILD.gn, renderer/BUILD.gn, typographer/BUILD.gn
Otherwise, depending on Impeller will cause an explicit dependency on
whatever VM variant :libdart picks. And, some other unit-test in the
engine explicitly link in the JIT variant which leads to duplicate
symbol errors in profile and release modes.
Towards fixing profile and release builds in https://github.com/flutter/engine/pull/31959
=> Only depend on FML for tracing when building executables.

renderer/backend/metal/render_pass_mtl.mm
For https://github.com/flutter/engine/pull/31959
=> Fix loop-range-construct warnings added in newer versions of Clang.

entity/contents/content_context.h, entity/entity.h, entity/entity_unittests.cc
This covers all of the remaining blends that are possible to implement using widely supported pipeline blend parameters. 
https://user-images.githubusercontent.com/919017/158262973-28a374c8-7c2a-4044-9de3-be2d0ad0e68c.mov
The other 15 blend modes must be implemented with fragment shaders or blend equation extensions (such as `GL_KHR_blend_equation_advanced` and `VK_EXT_blend_operation_advanced`) (see also: https://github.com/flutter/flutter/issues/100086))
=> Add remaining simple blend modes

geometry/scalar.h, geometry/vector.h, renderer/backend/metal/formats_mtl.h
Some like std::abs are not available till C++23. The others were
real warnings.
For https://github.com/flutter/engine/pull/31959
=> Fix issues with constexpr correctness.

renderer/backend/metal/render_pass_mtl.mm
Offset is a uint64_t that needs a cast.
For https://github.com/flutter/engine/pull/31959
=> Add cast necessary on 32-bit arm builds.

display_list/display_list_dispatcher.cc
Don't use `Add[Thing]` operations when emulating Skia path components because they intentionally insert `MoveTo`s.
We should probably refactor this to skip around PathBuilder altogether and convert Skia's path components more or less directly instead of using the `PathBuilder`, which exposes a more nuanced/complex interface to emulate Skia's user path building functionality.
=> Don't use `Add[Thing]` operations when emulating Skia path components

aiks/aiks_unittests.cc, entity/contents/clip_contents.cc
Some print debugging and GPU snapshots later, it turns out that all clip paths are supposed to be done in the current transform space, not screen space.
This can also be seen in the docs: https://api.skia.org/classSkCanvas.html#abc79bd478516f398c31ae9f501154184
https://user-images.githubusercontent.com/919017/158735467-76ea3fe3-24b2-46e6-9ecf-7f650eee858a.mov
=> Transform clips by the entity's transform

aiks/aiks_unittests.cc, aiks/canvas.cc
This fixes the transform for everything except the background in the [page flip example](https://github.com/bizz84/page_flip_builder). I don't see any more transform-related issues in either page flip or gallery.
=> Apply Aiks transforms in the canvas space, not world space

entity/shaders/glyph_atlas.frag, typographer/backends/skia/text_render_context_skia.cc
Also remove the debugging goop as that's only relevant if you can
visualize the background.
=> Use 8bpp glyph atlases.

aiks/aiks_unittests.cc, entity/contents/contents.cc, entity/contents/contents.h, entity/contents/filters/blend_filter_contents.cc, entity/contents/filters/blend_filter_contents.h, entity/contents/filters/filter_contents.cc, entity/contents/filters/filter_contents.h, entity/contents/filters/gaussian_blur_filter_contents.cc, entity/contents/filters/gaussian_blur_filter_contents.h, entity/contents/texture_contents.h, entity/entity.cc, entity/entity_unittests.cc, entity/shaders/texture_blend_screen.frag, entity/shaders/texture_blend_screen.vert, geometry/geometry_unittests.cc, geometry/geometry_unittests.h, geometry/matrix.cc, geometry/matrix.h, geometry/point.h, geometry/rect.h, geometry/scalar.h, geometry/size.h
This changes a lot about how the filters work and lines us up to make the paint image filter/advanced blends work. A lot of the changes here were made on the fly in order to avoid landing intermediary changes that reduce functionality.
Changes:
* All Contents can now compute their own screen space bounds given an entity/transform.
* FilterContents computes its bounds as the union of its inputs' bounds.
* As a consequence, `FilterContents` has enough information at render any contents to a texture at the correct end resolution, and so I extended filter inputs to allow for _any_ Contents type in addition to filters and textures. This will make supporting the paint filter very easy.
* The gaussian blur filter has a similar interface to Skia's blur now. And now that filters use correct …
=> Make the filter DAG render all textures at the correct resolution

aiks/aiks_unittests.cc, aiks/canvas.cc, aiks/canvas.h, display_list/display_list_dispatcher.cc, entity/contents/clip_contents.cc, entity/contents/clip_contents.h, entity/contents/content_context.cc, entity/contents/content_context.h, entity/entity.h
This works with two commands:
1. Increment the stencil area matching the current depth.
2. Decrement the stencil area matching the incremented depth and the given clip path.
My initial implementation was to just prepend a rectangle to the clip path (multiplied against the inverse transform so it ends up in the correct location to cover the entire render target) and let the tessellator do the inversion, but I didn't like how complex the geometry was that the tessellator was outputting and I didn't want to risk not covering corner cases, so I opted for this safer option instead.
Screenshot from the test, which uses difference clips to punch out the eyes/mouth, then restores the clip and draws a shape that partly covers the eyes:
=> Add difference clipping

aiks/paint.cc, aiks/paint.h, display_list/display_list_dispatcher.cc, display_list/display_list_unittests.cc
Also removes duplicate data during the path conversion (which are supplied by move components for new contours). was screwing up caps and joins).
* Left top: Butt cap + miter join with miter limit of 4.
* Left bottom: Butt cap + miter join with miter limit of 1.
* Middle: Square cap + bevel join.
* Right: Round cap + round join.
=> Wire up stroke cap/join/miter limit display list ops

entity/contents/linear_gradient_contents.cc
I noticed the tree shadows looked kind of inverted in the page flip example and checked out the linear gradient to see if we were managing colors right -- looks like I missed this one when switching everything to premultiplied source colors. 
Before:
After:
=> Premultiply gradient colors

entity/contents/filters/filter_contents.cc, entity/contents/filters/filter_contents.h, entity/contents/filters/gaussian_blur_filter_contents.cc, entity/contents/filters/gaussian_blur_filter_contents.h, entity/entity_unittests.cc, entity/shaders/gaussian_blur.frag, entity/shaders/gaussian_blur.vert
Includes/relies on the changes in https://github.com/flutter/impeller/pull/103. ~Use [this diff view](https://github.com/bdero/impeller/compare/bdero/filter-input...bdero:bdero/blur-style) to view this PR without the dependency.~
https://user-images.githubusercontent.com/919017/160531260-a3f3081e-2c7d-41b9-9c57-e95ea647f71e.mov
This involved an arduous debug session, but some screenshots that are kinda aesthetically pleasing came out of it along the way!
=> Add blur styles to gaussian blur

aiks/aiks_unittests.cc, entity/contents/solid_stroke_contents.cc, entity/contents/solid_stroke_contents.h
This test demonstrates a few solid stroke problems I'm investigating, but most notably: https://github.com/flutter/flutter/issues/101330
Corresponding Skia Fiddle:
https://fiddle.skia.org/c/027392122bec8ac2b5d5de00a4b9bbe2
=> Fix solid stroke contour switching + round cap smoothing, and add transparent path overdraw example

aiks/aiks_playground.cc, aiks/aiks_playground.h, aiks/aiks_unittests.cc, aiks/canvas.cc, entity/contents/contents.cc, entity/entity.cc, entity/entity_pass.cc, entity/entity_pass.h, entity/entity_unittests.cc, geometry/geometry_unittests.cc, geometry/rect.h
I spent some time investigating a bounds-related problem today that turned out to overlap with the SaveLayer issues, and decided to take a look at @chinmaygarde's [reduced test case](https://gist.github.com/chinmaygarde/f961483ec89b61b47d907b62f4f64ec3) while I was in the neighborhood (included in this PR).
1. Don't reset the current transform when calling SaveLayer.
2. Add guard for `std::optional` in `Contents::GetBounds` when fetching the path bounds -- this is nullopt for empty paths, and so all text rendering entities were computing garbage coverage.
3. Don't apply the recorded subpass transform when compositing the subpass texture. Instead, just position the path correctly in screen space.
4. Apply the screen space bounds offset to all entities in the entity pass tree and absorb the …
=> Fix SaveLayer/entity subpass behavioral problems

renderer/backend/metal/command_buffer_mtl.mm, renderer/renderer.cc
This is primarily useful in figuring out which render pass faulted vs which were merely affected by the fault. Since we already name our render passes appropriately, the traces seem fairly actionable.
=> Wire up enhanced command buffer error reporting.

renderer/backend/metal/command_buffer_mtl.mm
This is pending the addition of explicit synchronization primitives to
Impeller. It is unclear what the addition of such primitives would mean
to the future OpenGL ES backend.
=> Explicitly wait for subpass buffers to be scheduled.

base/BUILD.gn, base/base_unittests.cc, base/thread.cc, base/thread.h, base/thread_safety.cc, base/thread_safety.h, renderer/backend/metal/render_pass_mtl.mm, renderer/pipeline.cc, renderer/pipeline_builder.h, renderer/render_target.cc, renderer/vertex_buffer_builder.h, tools/impeller.gni
We used to use these extensively in the Flutter engine and I thought they
really worked really well. However, we depended on the thread safety
annotations being applied to libc++ utilities. Support for these is
incomplete. And as support improved, we could never really use them on
all platforms because we didn't control the libc++ implementation on the
platform. Instead of depending on a third party to provide annotated
utilities, bring in our own in Impeller.
Preps notification center and wiring up of concurrent render pass
encoders.
The confusion over when and where to use thread safety meant that
analysis may be disabled (or not enabled depending on toolchain
version). Explicitly enable analysis in Impeller TUs.
=> Add static thread safety analysis ready synchronization primitives.

entity/contents/contents.cc, entity/contents/contents.h, entity/contents/filters/filter_contents.cc, entity/contents/filters/filter_contents.h, entity/contents/filters/filter_input.cc, entity/contents/filters/filter_input.h, entity/contents/filters/gaussian_blur_filter_contents.cc, entity/contents/filters/gaussian_blur_filter_contents.h, entity/contents/snapshot.cc, entity/entity.cc, entity/entity.h, entity/entity_unittests.cc
We already use the term "coverage" in `Entity` and `EntityPass`, which I hadn't noticed when I started working on filters and adding per-contents `GetBounds`. This change unifies the "area of the screen that may be affected" concept around the term "coverage".
Also, we distinguish between no coverage and empty coverage everywhere by returning optionals, which we were already doing in a few places (see also [this comment](https://github.com/flutter/impeller/pull/111#discussion_r842081668)).
=> Standardize around "coverage" terminology; make coverage optional everywhere

aiks/canvas.cc, aiks/canvas.h, entity/contents/text_contents.cc, geometry/geometry_unittests.cc, geometry/matrix.h
Add an explicit Vector2 scale override in `Matrix` and `Canvas`.
So I ran into some confusion while adding imgui elements to the test for https://github.com/flutter/flutter/issues/101330. I set the canvas scale with `canvas.Scale({3, 3})`, which scaled everything correctly. However, to my dismay, `canvas.GetCurrentTransformation().Invert()` produced an identity matrix. The problem was that `canvas.Scale({x, y})` matches `Canvas::Scale(Vector3{x, y})`, and so the Z component of the Z basis vector gets set to zero, which means the determinant ends up being zero, which makes computing the inverse nonsensical. Having this explicit override makes this mistake much less likely.
(Also, drive-by fix: Move the text contents color premultiply into the render method for consistency with other …
=> Add explicit Point/Vector2 scaling methods to Matrix and Canvas

playground/imgui/imgui_impl_impeller.cc
Includes changes in https://github.com/flutter/impeller/pull/119.
Noticed the imgui renderer was respecting the clip stack in the playground while adding stuff to the test in https://github.com/flutter/flutter/issues/101330. ;)
=> Ignore the stencil in the imgui pipeline

aiks/aiks_unittests.cc, entity/contents/solid_color_contents.cc, entity/contents/solid_stroke_contents.cc, entity/entity_unittests.cc
Relies on changes in https://github.com/flutter/impeller/pull/120.
Fixes https://github.com/flutter/flutter/issues/101330.
* Render non-opaque solid strokes, incrementing the stencil to avoid overdraw.
* Return the stencil to its previous state by drawing a clip restore.
Before:
After:
https://user-images.githubusercontent.com/919017/162120700-b34e7adc-a3ab-4ad6-9613-fcfcee7d9e5b.mov
=> Fix solid stroke overdraw

entity/contents/filters/filter_contents.cc, entity/contents/filters/filter_contents.h, entity/contents/filters/gaussian_blur_filter_contents.cc, entity/contents/filters/gaussian_blur_filter_contents.h, entity/entity_unittests.cc, entity/shaders/gaussian_blur.frag, entity/shaders/gaussian_blur.vert
Use the constant that Flutter + Skia use for the kernel radius/distribution sample cutoff: `1/sqrt(3)`. The cutoff is just barely visible. In practice, we're free to make this conversion factor whatever we want (with diminishing returns).
Making it 3, for example, would cause the kernel convolution to cover at least 99.9% of the gaussian distribution.
Also fixes a mistake in the gaussian function (use the correct constant `1/sqrt(2*pi)` instead of `1/(2*pi)`).
=> Standardize around blur sigma<->radius conversion factor

compiler/compiler.cc
Fixes the issue I'm seeing locally where incremental builds end up giving errors like:
```
ninja: Entering directory `out/host_debug_unopt'
ninja: error: gen/flutter/impeller/entity/gradient_fill.frag.d: depfile mentions '../../flutter/impeller/entity/shaders/gradient_fill.frag' as an output, but no such output was declared
```
The depfile formatting goes from
```
gen/flutter/impeller/entity/gradient_fill.frag.metal: 
../../flutter/impeller/entity/shaders/gradient_fill.frag
```
to
```
gen/flutter/impeller/entity/gradient_fill.frag.metal: ../../flutter/impeller/entity/shaders/gradient_fill.frag
```
With the newline, ninja sometimes seems to think that the dependency is actually an ouput.
=> No newline in depfile output, which seems to confuse ninja

geometry/geometry_unittests.cc, geometry/path.cc, geometry/path_component.cc
Ran into this while making an override for the solid stroke coverage.
We incorporate the local min/max points for cubics by finding the roots of the first derivative of the x/y component cubics, but this doesn't end up enclosing the first/last point in most cases.
Demo of the issue (with the optional check to prevent the crash):
https://user-images.githubusercontent.com/919017/162394845-7b923333-0b32-47dc-867e-45a426367ebb.mov
The test I added creates a cubic with no derivative roots (it's just a line), which was causing `Path::GetBoundingBox` to crash before this change.
=> Fix Path::GetBoundingBox crash for cubics

entity/contents/solid_stroke_contents.cc, entity/contents/solid_stroke_contents.h, entity/entity_unittests.cc
Relies on the `Path::GetBoundingBox` fix in https://github.com/flutter/impeller/pull/126.
Currently, the stroke coverage is path coverage, and so it always gets cut off when used with SaveLayer or Filters without this change.
To get comprehensive coverage, it's necessary to take the transformed stroke width, `Cap::kButt`, and the miter limit into account.
Demo of the updated playground test (green rectangles are the coverage):
https://user-images.githubusercontent.com/919017/162400554-4f099872-4286-4326-a231-8224aa19c81e.mov
=> Add solid stroke coverage override

BUILD.gn, tools/impeller.gni
Fixes build issues seen in https://github.com/flutter/engine/pull/32658
Will require one change when rolling into the engine to guard header includes behind this new flag instead of the more generic one.
=> Move rendering TUs behind own flag

BUILD.gn, entity/BUILD.gn, renderer/backend/metal/command_buffer_mtl.mm
For https://github.com/flutter/engine/pull/32658
=> Build fixes for roll

aiks/paint.cc, entity/entity_unittests.cc
I started moving all the premultiplying of solid colors into Contents Render methods for consistency and accidentally added part of that change to https://github.com/flutter/impeller/pull/121, so at HEAD we're doubling up on the premultiply in the Render method for `Solid[Color|Stroke]Contents`.
=> Remove extra premultiply from solid stroke/fill

renderer/backend/metal/command_buffer_mtl.mm
I .. I forget how to write ObjC.
I'm going to let CI finish on https://github.com/flutter/engine/pull/32658 (which currently points to my fork) before landing this.
=> Fix enum typedef for older mac SDKs

entity/contents/contents.cc, entity/contents/contents.h, entity/contents/filters/blend_filter_contents.cc, entity/contents/filters/blend_filter_contents.h, entity/contents/filters/filter_contents.cc, entity/contents/filters/filter_contents.h, entity/contents/filters/filter_input.cc, entity/contents/filters/filter_input.h, entity/contents/filters/gaussian_blur_filter_contents.cc, entity/contents/filters/gaussian_blur_filter_contents.h, entity/contents/snapshot.cc, entity/contents/snapshot.h, entity/entity_unittests.cc, entity/shaders/texture_blend_screen.vert, geometry/geometry_unittests.cc, geometry/matrix.h, geometry/rect.h
Replace the `Snapshot` position (which held the position offset of the texture) with a transformation matrix, enabling raw texture `FilterInput`s to be consumed by the graph without pre-passes. The transform is respected equally for any input variant (`Contents` or `Texture`). This also allows for optimizing some less common situations. For example, [MatrixTransform](https://api.skia.org/classSkImageFilters.html#a81f98126fe53bc0bec517d356e805057) filters could just return the same snapshot (sampling mode permitting) except with a multiplied input texture.
Most of the changes here are to make the existing filters respect the transform:
* For basic blends, each input is drawn using a separate draw call, and so the transform is just applied to the geometry.
* For advanced blends and the …
=> Filters: Replace Snapshot position with a full transform

compiler/compiler.cc, compiler/compiler.h, compiler/compiler_unittests.cc, compiler/impellerc_main.cc, compiler/switches.cc, fixtures/BUILD.gn
The goal of this PR is to add support to impellerc for compiling glsl fragment shaders to SPIR-V such that they'll be accepted by the SPIR-V to SkSL transpiler in the Engine.
This will help migrate the hardcoded SPIR-V bytecode out of the framework at:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/ink_sparkle.dart#L690
and into a file asset: https://github.com/flutter/flutter/issues/99783.
Using impellerc for this rather than another tool will make it easier to generate the platform specific shaders to feed to the `FragmentProgram` API when Impeller is enabled because the Engine will only need to vend one additional binary. The next step after this PR is getting impellerc building on Linux and then Windows.
=> Adds --sksl target to impellerc

entity/BUILD.gn, entity/contents/content_context.cc, entity/contents/content_context.h, entity/contents/filters/border_mask_blur_filter_contents.cc, entity/contents/filters/border_mask_blur_filter_contents.h, entity/contents/filters/filter_contents.cc, entity/contents/filters/filter_contents.h, entity/entity_unittests.cc, entity/shaders/border_mask_blur.frag, entity/shaders/border_mask_blur.vert, geometry/matrix.h
Directly depends on changes in https://github.com/flutter/impeller/pull/130.
Adds a constant time mask blur for image borders.
This mask blur extends the geometry of the source image (with clamp border sampling) and applies a Gaussian blur to the original geometry mask.
The blur itself works by mapping the Gaussian distribution's indefinite integral (with a very close erf approximation) to the 4 edges of the UV rectangle and multiplying them.
https://user-images.githubusercontent.com/919017/163268514-cc9ea43a-0f73-4b00-b10a-dc490cc01a6f.mov
I'm planning a follow-up that allows filters to return snapshots, which will allow filters that don't modify coverage to do filtering into textures of the same size without having to worry about repositioning geometry/expanding contents. This way, we …
=> Border mask blur

aiks/aiks_unittests.cc, aiks/canvas.cc, aiks/paint_pass_delegate.cc, entity/contents/text_contents.cc, entity/contents/text_contents.h, entity/entity_pass.cc, entity/entity_pass.h, typographer/backends/skia/text_frame_skia.cc, typographer/text_frame.cc, typographer/text_frame.h
Compute text coverage by transforming the bounds pulled from the Skia text blob. Before it was just zero because we hand the entities empty paths when rendering text.
To write the Aiks test, some light yak shaving was necessary:
* Pipe blend mode through entity pass/save layer.
* Make subpass collapse/elision behavior more conservative... We can elide for `kDestination` blend, but the paint color doesn't help with either decision AFAIKT? Only by looking at all of the entities' blend modes would we actually be able to know the answer to this (if a pass and all of its children (subpasses and entities) have the same additive blend mode and no filter is present, we can collapse). I suggest we keep a "can_collapse" flag per-pass and do this check as entities are appended to the pass, so that …
=> Compute text coverage; use blend mode in savelayer; conservative pass collapse/elision behavior

aiks/aiks_unittests.cc, entity/entity_pass.cc, entity/entity_pass.h
Interleave Entities and Subpasses in `EntityPass`. Before this change, all subpasses would draw over all entities for the pass.
Minimal repro:
```
impeller_unittests --gtest_filter=Play/AiksTest.SaveLayerDrawsBehindSubsequentEntities/Metal --timeout=0
```
Skia fiddle: https://fiddle.skia.org/c/9e03de8567ffb49e7e83f53b64bcf636
Before:
After:
=> Fix EntityPass/SaveLayer draw ordering

BUILD.gn, blobcat/BUILD.gn, blobcat/blob.cc, blobcat/blob.h, blobcat/blob_library.cc, blobcat/blob_library.h, blobcat/blob_writer.cc, blobcat/blob_writer.h, blobcat/blobcat_main.cc, blobcat/blobcat_unittests.cc, compiler/compiler.cc, compiler/impellerc_main.cc, compiler/source_options.h, compiler/switches.cc, compiler/switches.h, entity/shaders/glyph_atlas.vert, fixtures/BUILD.gn, fixtures/instanced_draw.vert, playground/backend/metal/playground_impl_mtl.mm, playground/imgui/BUILD.gn, playground/imgui/imgui_raster.vert, tools/impeller.gni
* Dries up GN rules for Metal and OpenGL ES shader compilation and embedding in
a target binary.
* Adds support for shader compile time macro definitions. This is so that
workarounds for specific shader backends can be implemented. In the case of
this patch, there are temporary OpenGLES workaround for users of instancing
and SSBOs. These will be removed when I rework glyph rendering to not use
these features that are missing in legacy targets.
* Since there is no concept of an OpenGLES shader library akin to a `.metallib`,
adds a target called `blobcat` that concatenates shader blobs into single blob
that can be embedded into a target binary. No parsing or data copying is
necessary.
* `imgui_raster.vert` has been rewritten to work around the absence of unsigned
integer types in legacy …
=> Compile and package all shaders for the OpenGL ES backend.

aiks/canvas.cc, aiks/paint.cc, aiks/paint.h, display_list/display_list_dispatcher.cc, display_list/display_list_unittests.cc, entity/contents/contents.cc
We have 2 methods for achieving mask blur behavior:
- For images, use the BorderMaskBlurFilter, which is constant time per-fragment.
- For solid color fills, do a Gaussian blur, which is linear per-fragment, but does two subpasses. See below for future optimization ideas.
Future optimizations:
- Do `BorderMaskBlur` directly in the parent pass. Depending on the entity context, rendering into a subpass is unnecessary. This could also be done for the second gaussian blur pass. This is a feature I've been thinking about adding to `FilterContents`.
- For solid fills, trade GPU memory/time for CPU time: For the arbitrary path case, generate inset/outset geometry and give them distance coordinates. This isn't trivial for concave paths segments, but off the top of my head, I can think of a …
=> Implement mask blur in display list dispatcher

BUILD.gn, compiler/utilities.cc, display_list/display_list_unittests.cc, playground/playground.cc
Fixes some odds and ends to get this building on non-mac targets and make unit tests work (@bdero added a `TEST_F` after @chinmaygarde made changes that require `TEST_P`).
See flutter/engine#32819
=> Fix up build/test issues when building on or off of mac

entity/contents/filters/border_mask_blur_filter_contents.cc, entity/shaders/border_mask_blur.frag
This fixes a couple of issues I just noticed in the border mask blur.
1. Fix double-scaling problem with the sigma parameter. We use the inverse mapped "coverage UVs" of the input snapshot as the "border" in the border mask blur. Since we apply the mask blur over the UV space, it already takes into account the full transform, so I shouldn't have added that second scale in.
2. Slightly [scale and shift](https://www.desmos.com/calculator/xugr5njftx) the Gaussian integral such that it always has a root pretty close to the border radius, which makes the cutoff sloped, but not sudden.
Before (case where both issues are contributing to the badness):
After:
=> Fix border mask blur cutoff

BUILD.gn, blobcat/BUILD.gn, compiler/BUILD.gn, compiler/impellerc_main.cc
Depends on https://github.com/flutter/engine/pull/32846
Fixes https://github.com/flutter/flutter/issues/101866
Added the crash handler because at one point changes in the engine I made caused impellerc to segfault and I had no idea why :)
=> Remove dependency on Dart, add crash handler to impellerc

display_list/display_list_dispatcher.cc, display_list/display_list_dispatcher.h
Will unblock https://github.com/flutter/engine/pull/32159
cc @flar @chinmaygarde
=> Use New DlPathEffect Object

display_list/display_list_dispatcher.cc, display_list/display_list_dispatcher.h
Reverts flutter/impeller#98
This was pushed before the developer was ready to push the associated engine PR. It will be easy enough to reland when they (are ready to) rebase their PR.
Apologies @JsouLiang
=> Revert "Use New DlPathEffect Object"

entity/contents/filters/border_mask_blur_filter_contents.cc, entity/entity_unittests.cc
I noticed in passing that for some rotations, the corners were getting a bit cut off for some rotations. For example: At 45 degrees, the X axis of `transformed_blur_vector` was zero, even though it should be at its greatest length here (`sqrt((x + y)^2)`).
The incorrect version makes a diagonal vector from the input radii and rotates it by the basis matrix (which of course winds up being x=0 at 45 degrees). The corrected version takes the absolute value of each rotated axis _before_ adding them rather than after.
=> Another coverage fix for border mask blur

compiler/compiler_unittests.cc, compiler/reflector.cc, fixtures/BUILD.gn, fixtures/struct_def_bug.vert
Earlier, no PerVertexData struct would be generated. The shader is
useless without reflection information.
Fixes https://github.com/flutter/flutter/issues/102521.
=> Make it an error for a stage input to take more than one slot.

entity/contents/text_contents.cc, entity/shaders/glyph_atlas.vert, typographer/backends/skia/text_frame_skia.cc, typographer/text_frame.cc, typographer/text_run.cc, typographer/text_run.h
Makes the glyph_atlas.vert compile for GLES.
Does the following:
- Converts the SSBOs to per vertex data params
- Refactors GlyphPosition to use just a Point instead of a full matrix. Skia does support RSXform which would be 4 scalars, but AFAICT Flutter doesn't expose a way to use this today. If we need it someday we can support it, but we should not need a full matrix to do that (we can just use a vec4).
- Does not use the tessellator for the unit vector tessellation, instead just has a pre-built vertex array for it.
There are no new tests for this, just that the compiler now produces valid GLES shaders and removes some defines no-opping text for GLES.
=> Avoid instancing/SSBOs for text to support GLES
